name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.proto

      # Runs a single command using the runners shell
      - name: Generate Protobuf libraries
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          bash ./protoc.sh
